name: Luacheck
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Downloads .luacheckrc
        run: curl https://raw.githubusercontent.com/ZioPao/PaosZomboidCrap/main/.luacheckrc -o ${{ github.workspace }}/.luacheckrc
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
            args: media --config ${{ github.workspace }}/.luacheckrc